import type { Example } from './types';

export const advancedExamples: Example[] = [
  {
    id: 'A1',
    category: 'advanced',
    order: 1,
    title: 'Cross-chain Bridge',
    shortDescription: 'Lock on chain A, attest via validators, claim on chain B.',
    longDescription:
      `The canonical bridge pattern. Users lock tokens on chain A. A set of validators attests to the lock on chain B. Once the attestation threshold is reached, the user claims an equivalent amount on chain B.\n\nEvery bridge has the same shape — the attack surface lives in the validator trust assumption. Production bridges (Wormhole, LayerZero, Hyperlane) differ mainly in how they secure and rotate the validator set.`,
    difficulty: 'advanced',
    tags: ['bridges', 'cross-chain'],
    estimatedReadMinutes: 10,
    prerequisites: ['Understand multi-sig', 'Understand hash-based IDs'],
    tourLessons: ['M3L1'],
    sourcePath: '26-bridge.cov',
    whatToModify: [
      'Add validator rotation with a governance vote',
      'Add rate limits (max N locks per block) to cap exploit blast radius',
      'Support fee-paying claims (relayer covers gas, takes a cut)',
      'Slash validators who sign invalid attestations',
    ],
    relatedExamples: ['A5', 'D4'],
    docsLinks: [
      { title: 'Bridge Patterns', url: 'https://docs.covenant-lang.org/cookbook/bridges/' },
    ],
    deployable: true,
    gasEstimate: '~380k gas',
    usedInProduction: true,
  },
  {
    id: 'A2',
    category: 'advanced',
    order: 2,
    title: 'Diamond Storage (Upgradeability)',
    shortDescription: 'Namespaced storage slots for upgrade-safe state across modules.',
    longDescription:
      `Storage slots are derived from \`keccak(namespace)\`, not sequential from slot 0. Upgraded implementations can add new fields without ever conflicting with existing state. Covenant makes the namespace an attribute of the record rather than a hand-rolled struct-hash.\n\nThis is the safest pattern for upgradeable contracts — way less error-prone than OpenZeppelin's transparent proxy, and more composable than UUPS.`,
    difficulty: 'advanced',
    tags: ['upgradeability'],
    estimatedReadMinutes: 10,
    prerequisites: ['Understand storage layout', 'Understand proxy patterns'],
    tourLessons: ['M3L4'],
    sourcePath: '12-diamond-storage.cov',
    whatToModify: [
      'Add a third module and verify no storage collision',
      'Migrate a field between modules with a one-shot migration action',
      'Enforce namespace uniqueness at deploy time via attributes',
      'Build a storage-layout audit view that dumps all namespaces',
    ],
    relatedExamples: ['A3'],
    docsLinks: [
      { title: 'Diamond Pattern', url: 'https://docs.covenant-lang.org/cookbook/upgradeability/diamond/' },
    ],
    deployable: true,
    gasEstimate: '~420k gas',
    usedInProduction: true,
  },
  {
    id: 'A3',
    category: 'advanced',
    order: 3,
    title: 'Price Oracle',
    shortDescription: 'Chainlink-style price feed with staleness checks on every read.',
    longDescription:
      `External feeders push price updates. Any contract can read the current price along with a freshness timestamp. Reads revert if the price is stale beyond a configurable tolerance.\n\nThe staleness check is the defense against oracle-failure exploits. Never skip it: a stale price + leveraged position = liquidation loop. This example bakes it into \`get_price()\` so consumers can't accidentally read a frozen feed.`,
    difficulty: 'advanced',
    tags: ['oracles', 'integrations'],
    estimatedReadMinutes: 6,
    prerequisites: ['Understand time types', 'Understand roles'],
    tourLessons: ['M3L3'],
    sourcePath: '27-oracle.cov',
    whatToModify: [
      'Aggregate multiple feeders and use the median',
      'Reject price movements > X% between updates (circuit breaker)',
      'Emit a digest hash per update for off-chain light-client verification',
      'Add a TWAP view for consumers who need smoothed prices',
    ],
    relatedExamples: ['D5', 'A4'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~200k gas',
    usedInProduction: true,
  },
  {
    id: 'A4',
    category: 'advanced',
    order: 4,
    title: 'Uniswap V4 Hook',
    shortDescription: 'Custom hook for Uniswap V4 pool lifecycle callbacks.',
    longDescription:
      `Uniswap V4 introduces hooks: small contracts that run at key pool lifecycle points (beforeSwap, afterModifyLiquidity, etc). This example is a Covenant hook that plugs into a V4 pool.\n\nShowcases Covenant → Solidity interop: Covenant handles the core logic in a typed, declarative way; the hook ABI is auto-generated to match Uniswap's expected interface.`,
    difficulty: 'advanced',
    tags: ['defi', 'integrations'],
    estimatedReadMinutes: 12,
    prerequisites: ['Understand Uniswap V4', 'Understand hook callbacks'],
    tourLessons: ['M3L5'],
    sourcePath: '14-uniswap-hook.cov',
    whatToModify: [
      'Add a dynamic fee based on volatility',
      'Rebate a portion of fees to whitelisted users',
      'Add a before-swap MEV-protection check via commit-reveal',
      'Log per-swap analytics to an external aggregator contract',
    ],
    relatedExamples: ['D5', 'A3'],
    docsLinks: [
      { title: 'Uniswap V4 Hooks', url: 'https://docs.uniswap.org/contracts/v4/overview' },
    ],
    deployable: true,
    gasEstimate: '~600k gas (deploy + register)',
    usedInProduction: true,
  },
  {
    id: 'A5',
    category: 'advanced',
    order: 5,
    title: 'Shielded Token Bridge',
    shortDescription: 'Cross-chain transfer of FHE-encrypted tokens — amounts hidden end-to-end.',
    longDescription:
      `Combines the bridge pattern (A1) with FHE balances (P1). The amount crossing the bridge is encrypted end-to-end: no validator, no chain observer, no bridge operator can see transfer amounts. A ZK proof attached at claim time binds the ciphertext to a specific recipient without exposing the amount.\n\nThis is the holy grail of privacy-preserving interoperability. It is the category that Covenant's privacy stack enables natively — doing this in Solidity + Noir + ZK-SNARKs would take months of plumbing.`,
    difficulty: 'expert',
    tags: ['bridges', 'FHE', 'ZK'],
    estimatedReadMinutes: 15,
    prerequisites: ['Understand A1 Bridge', 'Understand P1 FHE', 'Understand P4 ZK'],
    tourLessons: ['M3L1'],
    sourcePath: '28-shielded-bridge.cov',
    whatToModify: [
      'Add a rate limit expressed in plaintext without revealing individual amounts',
      'Let users prove their balance-after-transfer is positive via ZK',
      'Add a regulatory viewing key for selective disclosure to auditors',
      'Chain two shielded bridges for multi-hop privacy',
    ],
    relatedExamples: ['A1', 'P1', 'P4'],
    docsLinks: [
      { title: 'Privacy Stack', url: 'https://docs.covenant-lang.org/guides/privacy-stack/' },
    ],
    deployable: true,
    gasEstimate: '~4M gas (FHE + ZK)',
    usedInProduction: false,
  },
];
