import type { Example } from './types';

export const basicsExamples: Example[] = [
  {
    id: 'B1',
    category: 'basics',
    order: 1,
    title: 'Hello Covenant',
    shortDescription: 'The minimal Covenant file — a record with one field and one action.',
    longDescription:
      `The simplest possible Covenant contract. Demonstrates the fundamentals: how to declare a record, store state in a field, and expose read/write capabilities through actions and views.\n\nIf you're new to Covenant, this is the right starting point. The syntax is declarative — no function keyword, no external/public modifiers, no need to think about visibility. The language infers what it needs.\n\nThis same skeleton forms ~70% of real-world contracts.`,
    difficulty: 'beginner',
    tags: ['basic', 'no-privacy', 'reference'],
    estimatedReadMinutes: 3,
    prerequisites: [],
    tourLessons: ['M1L1'],
    sourcePath: '01-hello.cov',
    whatToModify: [
      'Add a counter that tracks how many times the greeting was updated',
      'Restrict update to a whitelist (map<address, bool>)',
      'Add a timestamp showing when the greeting last changed',
      'Emit an event each time the greeting changes',
    ],
    relatedExamples: ['B2', 'B3'],
    docsLinks: [
      { title: 'First Contract Tutorial', url: 'https://docs.covenant-lang.org/getting-started/first-contract/' },
      { title: 'Actions and Views Reference', url: 'https://docs.covenant-lang.org/reference/language/actions-views/' },
    ],
    deployable: true,
    gasEstimate: '~90k gas (deploy)',
    usedInProduction: false,
  },
  {
    id: 'B2',
    category: 'basics',
    order: 2,
    title: 'Simple Counter',
    shortDescription: 'A number with increment/decrement, events, and a non-negative guard.',
    longDescription:
      `A step up from Hello Covenant. This contract tracks a number and allows anyone to increment or decrement it. Introduces mutable state, events, and the \`require\` guard that prevents the count from going negative.\n\nNote how actions are non-payable by default. If you want to accept Ether, you declare it explicitly — this makes security properties clearer than in Solidity, where \`payable\` is opt-out.`,
    difficulty: 'beginner',
    tags: ['basic', 'state'],
    estimatedReadMinutes: 3,
    prerequisites: ['Understand what a field is'],
    tourLessons: ['M1L1', 'M1L2'],
    sourcePath: '16-simple-counter.cov',
    whatToModify: [
      'Add a maximum limit that count cannot exceed',
      'Allow decrement only by the deployer',
      'Track total number of operations (increments + decrements)',
      'Add a reset action callable only by the owner',
    ],
    relatedExamples: ['B1', 'B5'],
    docsLinks: [
      { title: 'Guards Reference', url: 'https://docs.covenant-lang.org/reference/language/guards/' },
      { title: 'Events', url: 'https://docs.covenant-lang.org/reference/language/events/' },
    ],
    deployable: true,
    gasEstimate: '~110k gas (deploy)',
    usedInProduction: false,
  },
  {
    id: 'B3',
    category: 'basics',
    order: 3,
    title: 'Simple Coin',
    shortDescription: 'A standard ERC-20 token using the `token` construct.',
    longDescription:
      `The ERC-20 of Covenant. The \`token\` keyword synthesizes the entire transfer/approve/balance surface — you only write the metadata and any custom logic.\n\nFor an encrypted-balance version where amounts are private, see example P1 Confidential Payroll or the ERC-8227 implementation.`,
    difficulty: 'beginner',
    tags: ['basic', 'tokens'],
    estimatedReadMinutes: 4,
    prerequisites: ['Understand fields'],
    tourLessons: ['M1L1', 'M1L2', 'M1L3'],
    sourcePath: '02-coin.cov',
    whatToModify: [
      'Add a mint action restricted to the deployer (see D1 for the full pattern)',
      'Add a burn action that any holder can call',
      'Add a transfer fee that goes to a treasury address',
      'Track total number of holders dynamically',
    ],
    relatedExamples: ['D1', 'P1'],
    docsLinks: [
      { title: 'Token Construct', url: 'https://docs.covenant-lang.org/reference/stdlib/tokens/' },
      { title: 'ERC-8227 Encrypted Tokens', url: 'https://docs.covenant-lang.org/reference/ercs/erc-8227/' },
    ],
    deployable: true,
    gasEstimate: '~180k gas (deploy)',
    usedInProduction: true,
  },
  {
    id: 'B4',
    category: 'basics',
    order: 4,
    title: 'Types Reference',
    shortDescription: 'A non-functional contract demonstrating every Covenant primitive.',
    longDescription:
      `This contract doesn't do anything useful — it exists as a reference for the type system. Every primitive type is demonstrated side-by-side so you can copy the exact syntax for any field declaration.\n\nPay attention to the three privacy qualifiers: \`encrypted\` (FHE ciphertext), \`private\` (off-chain witness), \`sealed\` (MPC-sealed state). These map to the three ways Covenant hides data.`,
    difficulty: 'beginner',
    tags: ['basic', 'types', 'reference'],
    estimatedReadMinutes: 4,
    prerequisites: [],
    tourLessons: ['M1L4'],
    sourcePath: '17-types-reference.cov',
    whatToModify: [
      'Try changing u8_field to 256 and observe the compile error',
      'Add a new field of type map<bytes32, address>',
      'Create a custom struct type and declare a field of it',
      'Swap text_field for a tuple (text, amount) and update the view',
    ],
    relatedExamples: ['B1', 'B5'],
    docsLinks: [
      { title: 'Type System Reference', url: 'https://docs.covenant-lang.org/reference/language/types/' },
      { title: 'Privacy Qualifiers', url: 'https://docs.covenant-lang.org/reference/language/privacy/' },
    ],
    deployable: false,
    usedInProduction: false,
  },
  {
    id: 'B5',
    category: 'basics',
    order: 5,
    title: 'Vault (Actions vs Views)',
    shortDescription: 'Deposit/withdraw pattern showing actions (mutations) vs views (queries).',
    longDescription:
      `Understanding the distinction between actions and views is fundamental in Covenant. Actions cost gas, can mutate state, and are executed via transactions. Views are free, cannot mutate anything, and can be called off-chain.\n\nThis contract demonstrates both side-by-side. The clean separation means users always know what a call does: no hidden state changes in views (unlike Solidity, where a \`view\` can do unexpected things via inline assembly).`,
    difficulty: 'beginner',
    tags: ['basic', 'state', 'reference'],
    estimatedReadMinutes: 5,
    prerequisites: ['Understand maps'],
    tourLessons: ['M1L3'],
    sourcePath: '18-vault.cov',
    whatToModify: [
      'Add a withdrawAll action that drains the caller\'s entire balance',
      'Add a view returning the top-3 depositors',
      'Reject deposits that would push total_deposited above 1_000_000',
      'Split into read-only users and admin actions (restrict withdraw)',
    ],
    relatedExamples: ['D3', 'B3'],
    docsLinks: [
      { title: 'Actions Reference', url: 'https://docs.covenant-lang.org/reference/language/actions/' },
      { title: 'Views Reference', url: 'https://docs.covenant-lang.org/reference/language/views/' },
    ],
    deployable: true,
    gasEstimate: '~140k gas (deploy)',
    usedInProduction: true,
  },
];
