import type { Example } from './types';

export const defiExamples: Example[] = [
  {
    id: 'D1',
    category: 'defi',
    order: 1,
    title: 'Mintable Token',
    shortDescription: 'A token whose admin can create new supply — common in governance tokens.',
    longDescription:
      `Extends the basic token with minting capability. The deployer (or a multi-sig admin) can create new tokens and send them to any address. This pattern is common in DAO governance tokens, reward systems, and inflationary economics.\n\nPay attention to access control: only the admin can mint. In production, the admin is usually a multi-sig (D4) or a governance contract (G1), not a single EOA. Compare to B3 Simple Coin (fixed supply) — the security considerations change significantly once minting is possible.`,
    difficulty: 'intermediate',
    tags: ['tokens', 'governance'],
    estimatedReadMinutes: 5,
    prerequisites: ['Understand B3 Simple Coin'],
    tourLessons: ['M3L3'],
    sourcePath: '19-mintable-token.cov',
    whatToModify: [
      'Add a burn action that reduces total_supply',
      'Add a timelock on change_admin (must wait N days after proposing)',
      'Replace single admin with an array of authorized minters',
      'Track minting history with a map<time, amount>',
    ],
    relatedExamples: ['B3', 'D4', 'G1'],
    docsLinks: [
      { title: 'Access Control Patterns', url: 'https://docs.covenant-lang.org/cookbook/access-control/' },
    ],
    deployable: true,
    gasEstimate: '~210k gas (deploy)',
    usedInProduction: true,
  },
  {
    id: 'D2',
    category: 'defi',
    order: 2,
    title: 'Vesting Schedule',
    shortDescription: 'Linear token vesting with a cliff — for team tokenomics and investor allocations.',
    longDescription:
      `Classic vesting pattern: tokens are allocated at deploy time but claimable only over a schedule. Before the cliff, nothing vests. After the cliff, the entitled amount grows linearly until the end date.\n\nDemonstrates temporal guards (\`block.timestamp >= cliff\`) and computation of vested amounts based on elapsed time. Used universally for team equity, investor locks, and gradual distribution.`,
    difficulty: 'intermediate',
    tags: ['tokens', 'time'],
    estimatedReadMinutes: 6,
    prerequisites: ['Understand time types', 'Understand basic arithmetic'],
    tourLessons: ['M1L5'],
    sourcePath: '20-vesting.cov',
    whatToModify: [
      'Add cliff period with no vesting before cliff date',
      'Support multiple beneficiaries with different schedules',
      'Allow revocation of unvested tokens by admin',
      'Add accelerated vesting on a special event (M&A, ragequit)',
    ],
    relatedExamples: ['D1', 'D3'],
    docsLinks: [
      { title: 'Time-based Guards', url: 'https://docs.covenant-lang.org/reference/language/guards/#when' },
    ],
    deployable: true,
    gasEstimate: '~180k gas (deploy)',
    usedInProduction: true,
  },
  {
    id: 'D3',
    category: 'defi',
    order: 3,
    title: 'Time-locked Vault',
    shortDescription: 'Deposits are locked until a chosen unlock time chosen by each depositor.',
    longDescription:
      `Combines the deposit/withdraw pattern with per-user time locks. Each depositor picks their own lock expiry when depositing; extending is allowed, shortening is not. Useful for savings products, token locks during DAO votes, and scheduled releases.\n\nThe key constraint: \`unlock_time\` can only grow. This one-way monotonicity is a security primitive — attackers cannot shorten the lock even if they compromise the withdraw path.`,
    difficulty: 'intermediate',
    tags: ['defi', 'time', 'security'],
    estimatedReadMinutes: 5,
    prerequisites: ['Understand the vault pattern (B5)', 'Understand time guards'],
    tourLessons: ['M1L5'],
    sourcePath: '21-timelocked-vault.cov',
    whatToModify: [
      'Allow extending the lock period (already supported — try breaking it)',
      'Add emergency withdrawal with a 20% penalty',
      'Support multiple lock buckets per user with different unlock times',
      'Add a beneficiary who receives funds if caller misses a heartbeat check',
    ],
    relatedExamples: ['B5', 'D2'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~150k gas (deploy)',
    usedInProduction: true,
  },
  {
    id: 'D4',
    category: 'defi',
    order: 4,
    title: 'Multi-sig Admin',
    shortDescription: 'M-of-N signatures required for privileged actions — classic treasury pattern.',
    longDescription:
      `N out of M signers must approve each proposal before it executes. Used by DAO treasuries, bridge operators, and any organization requiring distributed authority.\n\nDemonstrates guard composition, mapping-based role management, and confirmation tracking. This is the pattern behind Gnosis Safe and every other serious treasury contract.`,
    difficulty: 'intermediate',
    tags: ['governance', 'security'],
    estimatedReadMinutes: 8,
    prerequisites: ['Understand access control', 'Understand maps'],
    tourLessons: ['M1L5', 'M3L4'],
    sourcePath: '04-multi-sig-admin.cov',
    whatToModify: [
      'Add spending limits per signer (each has a daily cap)',
      'Require different thresholds for different operation types',
      'Add a time delay between proposal and execution',
      'Support upgrading the signer set (with N-of-M approval)',
    ],
    relatedExamples: ['D1', 'G1', 'G4'],
    docsLinks: [
      { title: 'Multi-sig Pattern', url: 'https://docs.covenant-lang.org/cookbook/multi-sig/' },
    ],
    deployable: true,
    gasEstimate: '~320k gas (deploy)',
    usedInProduction: true,
  },
  {
    id: 'D5',
    category: 'defi',
    order: 5,
    title: 'Simple DEX (Constant Product)',
    shortDescription: 'A minimal x·y=k AMM — the pattern behind early Uniswap.',
    longDescription:
      `The constant-product market maker is the foundational pattern for automated exchanges. Given two token reserves X and Y, the product X·Y remains constant across swaps (ignoring fees).\n\nThis implementation is intentionally minimal — no impermanent-loss protection, no slippage limits, no LP tokens, no fees. Real production AMMs (Uniswap V4 with hooks) require significantly more complexity. Treat this as a teaching scaffold, not a production contract.`,
    difficulty: 'advanced',
    tags: ['defi'],
    estimatedReadMinutes: 10,
    prerequisites: ['Understand tokens', 'Understand basic math'],
    tourLessons: ['M3L5'],
    sourcePath: '22-simple-dex.cov',
    whatToModify: [
      'Add slippage protection (minimum output amount)',
      'Add swap fees that accrue to liquidity providers',
      'Support removing liquidity (and issue LP tokens)',
      'Add a time-weighted average price (TWAP) oracle view',
    ],
    relatedExamples: ['D1', 'A4'],
    docsLinks: [
      { title: 'DeFi Cookbook', url: 'https://docs.covenant-lang.org/cookbook/defi/' },
    ],
    deployable: true,
    gasEstimate: '~450k gas (deploy)',
    usedInProduction: true,
  },
];
