// E-series — Sprint 49 consolidated examples gallery
//
// 16 verified contracts replacing the previous 25-entry mix of working and
// broken examples. Sources are derived from compiler fixtures + 3 V0.9-new
// constructs + 3 showcase composition patterns.
//
// All sources live in `public/examples/E*.cov` and load lazily via the
// existing loader. All entries are tagged `compileStatus: 'verified'` —
// the inventory CI gate (`scripts/inventory-content.mjs --strict`) ensures
// every entry compiles end-to-end.

import type { Example } from './types';

export const eSeriesExamples: Example[] = [
  // ───────── Basics (3) ─────────
  {
    id: 'E01',
    category: 'basics',
    order: 1,
    title: 'Hello',
    shortDescription:
      'The minimal viable Covenant file: a record with one field, a setter action, and a getter view.',
    longDescription: `The simplest possible Covenant contract. Demonstrates the three building blocks every contract uses: a \`record\` type, a \`field\`, and an \`action\` paired with a \`view\`.

Notice the syntax compared to Solidity:

- Comments start with \`--\` (Haskell-style), not \`//\`.
- The top-level keyword is \`record\` — Covenant's minimal kv-store.
- Field declarations inside \`record\` don't need the \`field\` keyword (it's implicit).
- Views with zero arguments don't take parentheses: \`view read returns text\` (not \`view read() returns text\`).

The right starting point for any Covenant developer.`,
    difficulty: 'beginner',
    tags: ['basic', 'no-privacy', 'reference'],
    estimatedReadMinutes: 3,
    prerequisites: [],
    tourLessons: ['M1L1'],
    sourcePath: 'E01-hello.cov',
    whatToModify: [
      'Add a `field updates: amount = 0` and increment it inside `update`.',
      'Add a `view last_updater returns address` (with `field last_updater: address`).',
      'Restrict `update` to the deployer with `when caller == deployer`.',
      'Emit an event each time the greeting changes.',
    ],
    relatedExamples: ['E02', 'E03'],
    docsLinks: [
      { title: 'Real Covenant Syntax (V0.9)', url: 'https://covenant-lang.org/docs/examples/01-hello-contract' },
      { title: 'docs.covenant-lang.org', url: 'https://docs.covenant-lang.org' },
    ],
    deployable: true,
    gasEstimate: '~80k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E02',
    category: 'basics',
    order: 2,
    title: 'Coin (ERC-20)',
    shortDescription:
      'A standard ERC-20 token. The `token` keyword auto-synthesizes the entire ERC-20 surface from just metadata.',
    longDescription: `An ERC-20-conformant token in 6 lines of code. The \`token\` keyword auto-synthesizes:

- **Fields**: \`supply\`, \`balances\`, \`allowances\`, \`name\`, \`symbol\`, \`decimals\`
- **Actions**: \`transfer\`, \`approve\`, \`transfer_from\`
- **Views**: \`balance_of\`, \`allowance\`, \`total_supply\`, \`name\`, \`symbol\`, \`decimals\`
- **Events**: \`Transfer\`, \`Approval\`

\`supply: 1_000_000 to deployer\` mints 1M tokens at deploy time to the deployer's balance.

To customize: write your own \`action transfer(...) { ... }\` after the metadata. The synthesis honors your override.`,
    difficulty: 'beginner',
    tags: ['tokens', 'reference'],
    estimatedReadMinutes: 4,
    prerequisites: ['Read E01 — Hello first'],
    tourLessons: ['M1L1', 'M1L2', 'M3L4'],
    sourcePath: 'E02-coin.cov',
    whatToModify: [
      'Change the symbol and name to your own token.',
      'Change `decimals: 18` to `decimals: 6` (USDC-style).',
      'Change supply to a different number (try `100_000_000` for 100M).',
      'Add a custom `action burn(value: amount) { /* ... */ }`.',
    ],
    relatedExamples: ['E01', 'E03', 'E05', 'E15'],
    docsLinks: [
      { title: 'ERC-20 spec', url: 'https://eips.ethereum.org/EIPS/eip-20' },
    ],
    deployable: true,
    gasEstimate: '~450k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E03',
    category: 'basics',
    order: 3,
    title: 'Safe Transfer',
    shortDescription:
      'Typed errors, revert_with, and guarded withdrawals — Covenant\'s error pattern.',
    longDescription: `Covenant errors are typed (like Solidity 0.8.4+ custom errors), with ABI-compatible selectors generated by the compiler.

This example demonstrates:

- \`error InsufficientBalance(...)\` declarations alongside fields and actions
- \`when\` guards on actions (the idiomatic way)
- \`only owner\` access control
- The interplay between guards and the \`revert_with\` pattern

When a \`when\` guard fails, the action reverts with a generic message. When you need specific error data, use \`revert_with\` in the action body.`,
    difficulty: 'beginner',
    tags: ['security', 'reference', 'no-privacy'],
    estimatedReadMinutes: 5,
    prerequisites: ['Read E01 — Hello'],
    tourLessons: ['M3L2'],
    sourcePath: 'E03-safe-transfer.cov',
    whatToModify: [
      'Add a `pause()` action that sets a `field paused: bool` to true.',
      'Add a guard `when !paused` to all withdraw actions.',
      'Add a `withdraw_all() only owner` action.',
    ],
    relatedExamples: ['E02', 'E07'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~150k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },

  // ───────── Privacy (3) ─────────
  {
    id: 'E04',
    category: 'privacy',
    order: 4,
    title: 'Shielded Counter',
    shortDescription:
      'An FHE-encrypted counter — homomorphic addition without decryption. The simplest private contract.',
    longDescription: `Your first private state. The \`encrypted counter\` construct stores its field as a TFHE ciphertext on-chain. Operations like \`+=\` work directly on the encrypted data without ever decrypting it.

Nobody — not validators, not block explorers, not anyone reading the chain — can see what \`count\` actually is. Only the principal listed in the \`reveal\` declaration can decrypt.

This is the foundation of every privacy-preserving Covenant pattern: encrypted balances, private votes, hidden state.`,
    difficulty: 'intermediate',
    tags: ['FHE', 'state', 'reference'],
    estimatedReadMinutes: 4,
    prerequisites: ['E01 — Hello'],
    tourLessons: ['M2L1'],
    sourcePath: 'E04-shielded-counter.cov',
    whatToModify: [
      'Add a `decrement` action that subtracts 1.',
      'Change `reveal count to deployer` to `reveal count to owner` (and add a `field owner: address`).',
      'Add a `bump_by(n: amount)` that adds n to count.',
    ],
    relatedExamples: ['E05', 'E06'],
    docsLinks: [
      { title: 'ERC-8227 (Confidential tokens)', url: 'https://covenant-lang.org/docs/examples/07-fhe-basics' },
    ],
    deployable: true,
    gasEstimate: '~200k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E05',
    category: 'privacy',
    order: 5,
    title: 'Secret Coin (ERC-8227)',
    shortDescription:
      'A confidential token — encrypted balances on-chain. Same surface as ERC-20 but nobody can see who owns what.',
    longDescription: `\`confidential token\` does for privacy what \`token\` does for ERC-20: 5 lines of metadata become a complete ERC-8227 surface.

Auto-synthesized: \`transferEncrypted\`, \`balanceOfEncrypted\`, \`approveEncrypted\`, \`TransferEncrypted\` event. Transfer amounts are ciphertexts; balances are ciphertexts. The EVM executes operations homomorphically.

Use cases: confidential payroll, hidden treasury, private trading, regulatory compliance with selective disclosure.`,
    difficulty: 'intermediate',
    tags: ['tokens', 'FHE', 'reference'],
    estimatedReadMinutes: 5,
    prerequisites: ['E02 — Coin', 'E04 — Shielded Counter'],
    tourLessons: ['M2L2'],
    sourcePath: 'E05-secret-coin.cov',
    whatToModify: [
      'Change supply, name, symbol.',
      'Add a `mint(to: address, value: encrypted amount) only deployer` action.',
      'Add a custom \`reveal balance to <special_role>\` for a regulator pattern.',
    ],
    relatedExamples: ['E02', 'E04', 'E06'],
    docsLinks: [
      { title: 'ERC-8227', url: 'https://covenant-lang.org/docs/reference/ercs/02-erc-8227-fhe' },
    ],
    deployable: true,
    gasEstimate: '~600k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E06',
    category: 'privacy',
    order: 6,
    title: 'Private DAO',
    shortDescription:
      'Encrypted governance — hidden vote tallies until reveal. Private votes via encrypted counters.',
    longDescription: `Encrypted governance. Each vote is an encrypted +1 to one of three counts (yes / no / abstain). Nobody can see the running tally during the vote. Once the deadline passes, the deployer reveals the results.

Demonstrates the privacy + access control combination: \`encrypted counter\` for hidden state, \`only first_time_caller\` for one-vote-per-address, \`reveal X to deployer\` for the result.`,
    difficulty: 'intermediate',
    tags: ['FHE', 'governance', 'recovery'],
    estimatedReadMinutes: 6,
    prerequisites: ['E04 — Shielded Counter'],
    tourLessons: ['M2L5'],
    sourcePath: 'E06-private-dao.cov',
    whatToModify: [
      'Add a deadline using `field opened_at: time = now` and `field duration: duration = 7 days`.',
      'Guard `vote_*` actions with `when now < opened_at + duration`.',
      'Add a `view total_votes returns amount` (after reveal).',
    ],
    relatedExamples: ['E04', 'E07'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~500k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },

  // ───────── Advanced (4) ─────────
  {
    id: 'E07',
    category: 'advanced',
    order: 7,
    title: 'Open Ballot',
    shortDescription:
      'Time-bounded vote with multiple guards: deadline, single-vote, valid choice. The canonical ballot pattern.',
    longDescription: `Public voting via the \`ballot\` construct. The compiler auto-synthesizes \`tally\` (a map<choice, amount>), \`opened_at\` (deploy timestamp), and the \`Cast\` event.

Demonstrates the canonical Covenant guard composition:

- \`when now < opened_at + duration\` — deadline enforcement
- \`only first_time_caller\` — one-vote-per-address
- \`given pick in options\` — choice validation

The \`reveal winner\` exposes the result only after the vote closes (\`when now >= opened_at + duration\`).`,
    difficulty: 'advanced',
    tags: ['governance', 'time', 'state'],
    estimatedReadMinutes: 8,
    prerequisites: ['E03 — Safe Transfer', 'E06 — Private DAO'],
    tourLessons: ['M3L1'],
    sourcePath: 'E07-open-ballot.cov',
    whatToModify: [
      'Change duration to `1 hour` for quick testing.',
      'Add a `quorum: amount = 100` field and a guard `when sum(tally) >= quorum` on `winner`.',
      'Add a fourth choice "delegate" and handle it specially.',
    ],
    relatedExamples: ['E06', 'E14'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~700k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E08',
    category: 'advanced',
    order: 8,
    title: 'Amnesia Ceremony',
    shortDescription:
      'ERC-8228 — provably destroy keys. Setup, finalize, destroy. No recovery. Live on Sepolia in V0.9.',
    longDescription: `Cryptographic amnesia. The \`ceremony\` construct generates the entire ERC-8228 lifecycle: setup → submit_share → finalize → destroy.

After \`destroy()\`, the keys are **provably unrecoverable** — a Wesolowski VDF proof binds destruction to a specific keccak output. Anyone can verify the destruction proof on-chain.

V0.9 milestone (M1): the first ceremony destruction on Sepolia is live at [0x2FB87d54...](https://sepolia.etherscan.io/address/0x2FB87d54). Deploy this contract, run the lifecycle, and your destruction proof joins it.`,
    difficulty: 'expert',
    tags: ['Amnesia', 'ZK', 'cross-chain'],
    estimatedReadMinutes: 12,
    prerequisites: ['E04 — Shielded Counter'],
    tourLessons: ['M2L4', 'M4L5'],
    sourcePath: 'E08-amnesia-ceremony.cov',
    whatToModify: [
      'Increase `guardians: 5, threshold: 3` for stronger Byzantine tolerance.',
      'Try `guardians: 1, threshold: 1` to model a single-key ceremony (no sharding).',
      'Add a `view ceremony_owner returns address { owner() }`.',
      'Remove the `on_destroy` block and observe the lifecycle still works.',
    ],
    relatedExamples: ['E16', 'E09'],
    docsLinks: [
      { title: 'ERC-8228', url: 'https://covenant-lang.org/docs/reference/ercs/03-erc-8228-amnesia' },
      { title: 'M1 milestone (Etherscan)', url: 'https://sepolia.etherscan.io/address/0x2FB87d54' },
    ],
    deployable: true,
    gasEstimate: '~1.2M gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E09',
    category: 'advanced',
    order: 9,
    title: 'Encrypted Bridge',
    shortDescription:
      'Cross-chain escrow pattern with lock/unlock and balance guards. The canonical bridge architecture.',
    longDescription: `A module-based escrow. Lock assets on this chain; off-chain watchers observe the \`Locked\` event and release on a target chain. Unlocks require a prior lock (enforced by the \`when deposits[caller] >= value\` guard).

Demonstrates:

- \`map<address, amount>\` for per-user state
- Event-driven cross-chain choreography
- Balance-conservation guards
- View functions exposing aggregate state`,
    difficulty: 'advanced',
    tags: ['bridges', 'cross-chain', 'state'],
    estimatedReadMinutes: 8,
    prerequisites: ['E03 — Safe Transfer'],
    tourLessons: ['M3L3'],
    sourcePath: 'E09-encrypted-bridge.cov',
    whatToModify: [
      'Add a `field paused: bool = false` and a `pause() only owner` action.',
      'Add a `lock_with_attestation(value: amount, sig: bytes)` for off-chain attestations.',
      'Replace `field deposits: map<address, amount>` with `field encrypted deposits: map<address, encrypted amount>`.',
    ],
    relatedExamples: ['E03', 'E15'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~600k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E10',
    category: 'advanced',
    order: 10,
    title: 'Quantum Board',
    shortDescription:
      'Append-only message board with Dilithium-5 signature verification. Future-proof message authenticity.',
    longDescription: `An append-only board where every post is verified with a **post-quantum signature** (Dilithium-5 per FIPS 204).

Each user registers a \`pq_key\` once. Subsequent submissions carry a Dilithium signature over the post content. The compiler's \`pq_signed\` guard verifies the signature inline; if invalid, the action reverts before the body runs.

This is the migration path for any signature-bearing contract: when ECDSA is broken (when, not if), Dilithium-protected accounts continue to work.`,
    difficulty: 'advanced',
    tags: ['PQ', 'identity', 'security'],
    estimatedReadMinutes: 10,
    prerequisites: ['E01 — Hello'],
    tourLessons: ['M2L3'],
    sourcePath: 'E10-quantum-board.cov',
    whatToModify: [
      'Add a `delete_post(idx: amount)` guarded by `pq_signed` over the index.',
      'Add a `field max_posts: amount = 100` and a guard `when count(posts) < max_posts`.',
      'Add a moderation field `field banned: map<address, bool>` and a `when !banned[caller]` guard.',
    ],
    relatedExamples: ['E12', 'E03'],
    docsLinks: [
      { title: 'ERC-8231 PQ Registry', url: 'https://covenant-lang.org/docs/reference/ercs/05-erc-8231-pq' },
    ],
    deployable: true,
    gasEstimate: '~800k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },

  // ───────── V0.9 New (3) ─────────
  {
    id: 'E11',
    category: 'v09',
    order: 11,
    title: 'NFT Collection',
    shortDescription:
      'ERC-721 auto-synthesized from 5 lines — mint, transfer, approve, metadata. The V0.9 way.',
    longDescription: `V0.9 introduces \`nft\` — a top-level construct that auto-synthesizes the entire ERC-721 surface from metadata only.

Auto-synthesized:
- **Fields**: \`owners\`, \`balances\`, \`token_approvals\`, \`operator_approvals\`
- **Views**: \`name\`, \`symbol\`, \`tokenURI\`, \`balanceOf\`, \`ownerOf\`, \`getApproved\`, \`isApprovedForAll\`
- **Actions**: \`approve\`, \`setApprovalForAll\`, \`transferFrom\`, \`mint\`
- **Events**: \`Transfer\`, \`Approval\`, \`ApprovalForAll\`

V0.9.0 limits: \`mint\` is open-access (add \`only deployer\` to gate), \`tokenURI(id)\` returns \`base_uri\` verbatim (id concat in V0.9.x), \`safeTransferFrom\` reserved but not yet emitted.`,
    difficulty: 'beginner',
    tags: ['tokens', 'reference'],
    estimatedReadMinutes: 4,
    prerequisites: ['E02 — Coin'],
    tourLessons: ['M4L1'],
    sourcePath: 'E11-nft.cov',
    whatToModify: [
      'Change `name` and `symbol` — the contract still compiles.',
      'Add `field minted_count: u256` and increment on each mint.',
      'Add `only deployer` to the synthesized mint by re-declaring it inline.',
      'Change `base_uri` to `"ipfs://Qm..."` for IPFS metadata.',
    ],
    relatedExamples: ['E02', 'E12'],
    docsLinks: [
      { title: 'Docs: NFT', url: 'https://covenant-lang.org/docs/examples/16-nft' },
    ],
    deployable: true,
    gasEstimate: '~1.2M gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E12',
    category: 'v09',
    order: 12,
    title: 'PQ Key Registry',
    shortDescription:
      'ERC-8231 post-quantum key registry — register, update, revoke. One-line declaration.',
    longDescription: `V0.9's \`registry\` keyword auto-synthesizes ERC-8231 — the post-quantum key registry standard. The migration vehicle from ECDSA to Dilithium-5.

Auto-synthesized:
- **Fields**: \`keys: map<address, pq_key>\`, \`registered: map<address, bool>\`
- **Views**: \`is_registered(account)\`, \`key_of(account)\`, \`algorithm_id()\`
- **Actions**: \`register(pk: pq_key)\`, \`revoke()\`
- **Events**: \`KeyRegistered\`, \`KeyRevoked\`, \`KeyUpdated\` (reserved)

\`algorithm_id()\` returns 1 (Dilithium-5 per FIPS 204). V1.0 may add Falcon-512, SPHINCS+, or hybrid IDs.`,
    difficulty: 'beginner',
    tags: ['PQ', 'identity', 'reference'],
    estimatedReadMinutes: 4,
    prerequisites: ['E10 — Quantum Board'],
    tourLessons: ['M4L2'],
    sourcePath: 'E12-registry.cov',
    whatToModify: [
      'Add `field approved: map<address, bool>` and gate `register` with `given approved[caller]`.',
      'Add a `view total_registered returns u256`.',
      'Add a custom `revoke()` requiring a PQ signature.',
    ],
    relatedExamples: ['E10', 'E11'],
    docsLinks: [
      { title: 'Docs: Registry', url: 'https://covenant-lang.org/docs/examples/17-registry' },
      { title: 'ERC-8231', url: 'https://covenant-lang.org/docs/reference/ercs/05-erc-8231-pq' },
    ],
    deployable: true,
    gasEstimate: '~600k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E13',
    category: 'v09',
    order: 13,
    title: 'Cross-Contract Call',
    shortDescription:
      'Call another contract via typed `interface` + `call_interface`. Type-checked at compile time.',
    longDescription: `V0.9 introduces \`interface\` — a top-level declaration that defines the surface of an external contract for typed cross-contract calls.

Why this matters: Solidity's \`address.call(bytes)\` is untyped — you encode arguments by hand and the compiler can't tell you when you got it wrong. Covenant's \`interface\` declarations solve that:

- **Type-checked at compile time.** Wrong types → compile error.
- **No selector typos.** Selector is computed from the interface, not from a string.
- **Auto-decode on return.** \`iface.balance_of(addr)\` returns \`amount\` directly.

\`call_interface(addr, IFaceName)\` creates a typed handle. Method calls compile to real EVM CALL opcodes. Views compile to STATICCALL. Default reentrancy protection on all external calls.`,
    difficulty: 'intermediate',
    tags: ['integrations', 'cross-chain', 'advanced-patterns'],
    estimatedReadMinutes: 8,
    prerequisites: ['E03 — Safe Transfer'],
    tourLessons: ['M4L3'],
    sourcePath: 'E13-cross-contract.cov',
    whatToModify: [
      'Add a `view get_token_balance() returns amount` calling `iface.balance_of(self)`.',
      'Add a precondition `given iface.balance_of(self) >= value` before transfer.',
      'Define a second interface `IFactory` and use both in the same module.',
    ],
    relatedExamples: ['E15', 'E03'],
    docsLinks: [
      { title: 'Docs: Interfaces', url: 'https://covenant-lang.org/docs/examples/18-external-call' },
    ],
    deployable: true,
    gasEstimate: '~400k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },

  // ───────── Showcase (3) ─────────
  {
    id: 'E14',
    category: 'showcase',
    order: 14,
    title: 'Hybrid State',
    shortDescription:
      'Mixed privacy — some fields public, some encrypted, in one contract. The hybrid module pattern.',
    longDescription: `\`hybrid module\` allows per-field privacy qualifiers. Some state is visible (counts, status, timestamps); some is encrypted (balances, salaries, sensitive amounts).

This is the practical pattern for most real applications: you can't make everything encrypted (gas costs, transparency requirements), and you don't want everything public (privacy requirements). \`hybrid module\` lets you choose per field.`,
    difficulty: 'advanced',
    tags: ['FHE', 'state', 'advanced-patterns'],
    estimatedReadMinutes: 8,
    prerequisites: ['E04 — Shielded Counter', 'E05 — Secret Coin'],
    tourLessons: ['M3L5'],
    sourcePath: 'E14-hybrid-state.cov',
    whatToModify: [
      'Add another encrypted field and a corresponding reveal statement.',
      'Add a public counter that increments alongside encrypted state.',
      'Add a `reveal X to multiple_principals` (if supported).',
    ],
    relatedExamples: ['E05', 'E06'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~700k gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E15',
    category: 'showcase',
    order: 15,
    title: 'Token + Withdrawer',
    shortDescription:
      'Composition pattern — a module that calls a token via interface. The V0.9 DeFi primitive.',
    longDescription: `Two contracts in one file demonstrating the canonical composition: a \`token\` (ERC-20 auto-synthesis) + a \`module\` that calls into it via a typed \`interface\` declaration.

This is the V0.9 way to wire DeFi protocols, treasury contracts, and any module that needs to move tokens. The token and the module compile to two separate bytecode artifacts; the module calls the token at runtime via the interface handle.`,
    difficulty: 'advanced',
    tags: ['integrations', 'tokens', 'advanced-patterns'],
    estimatedReadMinutes: 8,
    prerequisites: ['E02 — Coin', 'E13 — Cross-Contract Call'],
    tourLessons: ['M4L3'],
    sourcePath: 'E15-token-withdrawer.cov',
    whatToModify: [
      'Add a `set_admin(new: address) only admin` action.',
      'Add a `view treasury_balance returns amount` using `iface.balance_of(self)`.',
      'Add an `emergency_withdraw_all() only admin` action.',
    ],
    relatedExamples: ['E02', 'E13'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~1.5M gas (deploy both)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
  {
    id: 'E16',
    category: 'showcase',
    order: 16,
    title: 'Full Ceremony',
    shortDescription:
      'Complete ceremony lifecycle — deploy, setup, submit shares, finalize, destroy. Sepolia-ready.',
    longDescription: `A complete amnesia ceremony, ready to deploy on Sepolia via the helper-contract bridge.

The full lifecycle:

1. **setup()** — initialize ceremony, generate session
2. **submit_share()** — guardians submit Shamir shares (threshold reached when N submitted)
3. **finalize()** — close share collection
4. **destroy()** — emit irrevocable destruction proof (Wesolowski VDF)

V0.9 milestone: this lifecycle executes on real Sepolia. The M1 milestone on Etherscan (0x2FB87d54...) is the first ceremony destruction ever verified on a live network. Deploy this contract on Sepolia and your destruction proof joins it.`,
    difficulty: 'expert',
    tags: ['Amnesia', 'cross-chain', 'reference'],
    estimatedReadMinutes: 15,
    prerequisites: ['E08 — Amnesia Ceremony'],
    tourLessons: ['M4L5'],
    sourcePath: 'E16-full-ceremony.cov',
    whatToModify: [
      'Switch the playground target to Sepolia and deploy this for real.',
      'Increase guardians: 7, threshold: 5 for higher security.',
      'Add a `view threshold_met returns bool` exposing internal state.',
    ],
    relatedExamples: ['E08'],
    docsLinks: [
      { title: 'M1 Milestone (Etherscan)', url: 'https://sepolia.etherscan.io/address/0x2FB87d54' },
      { title: 'V0.9 Helper Bridge', url: 'https://covenant-lang.org/docs/changelog-v09' },
    ],
    deployable: true,
    gasEstimate: '~1.4M gas (deploy)',
    usedInProduction: false,
    compileStatus: 'verified',
  },
];
