import type { Example } from './types';

export const governanceExamples: Example[] = [
  {
    id: 'G1',
    category: 'governance',
    order: 1,
    title: 'DAO Basic',
    shortDescription: 'Token-weighted DAO with propose, vote, and execute phases.',
    longDescription:
      `The canonical on-chain DAO pattern. Any token holder can create a proposal. Voting weight is proportional to token balance. After the voting window closes, anyone can execute the proposal if quorum and majority are met.\n\nThis is the skeleton behind Compound, Uniswap, and most governance systems. Real production DAOs layer on timelocks (G2), delegation (G3), and veto mechanisms.`,
    difficulty: 'intermediate',
    tags: ['governance'],
    estimatedReadMinutes: 8,
    prerequisites: ['Understand tokens', 'Understand maps and structs'],
    tourLessons: ['M3L3'],
    sourcePath: '23-dao-basic.cov',
    whatToModify: [
      'Add a proposal threshold (minimum token balance to create one)',
      'Add a cancellation path before voting starts',
      'Support multiple options instead of yes/no (ranked-choice)',
      'Add a veto role that can kill malicious proposals before execution',
    ],
    relatedExamples: ['G2', 'G3', 'P3'],
    docsLinks: [
      { title: 'Governance Cookbook', url: 'https://docs.covenant-lang.org/cookbook/governance/' },
    ],
    deployable: true,
    gasEstimate: '~480k gas (deploy)',
    usedInProduction: true,
  },
  {
    id: 'G2',
    category: 'governance',
    order: 2,
    title: 'Time-Locked Admin',
    shortDescription: 'Queue, 48-hour delay, execute — governance-grade change control.',
    longDescription:
      `Admin actions are queued with a mandatory delay before execution. Users see the pending change and can exit if they disagree. Standard in DeFi where any sudden admin action could rug users.\n\nThe delay is non-negotiable: even the admin who queued the action can't bypass it. Combine with multi-sig (D4) for defense-in-depth.`,
    difficulty: 'intermediate',
    tags: ['governance', 'time', 'security'],
    estimatedReadMinutes: 6,
    prerequisites: ['Understand guards', 'Understand time'],
    tourLessons: ['M1L5'],
    sourcePath: '05-time-locked-admin.cov',
    whatToModify: [
      'Add a cancellation path for queued actions',
      'Different delays for different operation sensitivity levels',
      'A grace window after the delay during which execution is allowed',
      'A veto role (e.g. guardian) that can kill a queued action',
    ],
    relatedExamples: ['D4', 'G1'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~220k gas',
    usedInProduction: true,
  },
  {
    id: 'G3',
    category: 'governance',
    order: 3,
    title: 'Vote Delegation',
    shortDescription: 'Delegate your voting power to a representative who votes on your behalf.',
    longDescription:
      `Most token holders don't actively vote. Delegation lets them point their voting power at a representative who does. The delegate accumulates weight from everyone who delegated to them.\n\nCombined with G1 (DAO Basic), this is the complete Compound-style governance stack. Real production systems add snapshot blocks to prevent flash-loan-assisted voting attacks.`,
    difficulty: 'intermediate',
    tags: ['governance', 'advanced-patterns'],
    estimatedReadMinutes: 6,
    prerequisites: ['Understand G1 DAO', 'Understand tokens'],
    tourLessons: ['M3L3'],
    sourcePath: '24-vote-delegation.cov',
    whatToModify: [
      'Snapshot voting weight at proposal creation (prevent flash-loan attacks)',
      'Support partial delegation (X% to one delegate, Y% to another)',
      'Track delegation history for an activity leaderboard',
      'Add delegate profiles (name, statement, URL)',
    ],
    relatedExamples: ['G1', 'G2'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~180k gas',
    usedInProduction: true,
  },
  {
    id: 'G4',
    category: 'governance',
    order: 4,
    title: 'Amnesia Ceremony',
    shortDescription: 'Provably destroy deployment keys via a one-way MPC + VDF ceremony (ERC-8228).',
    longDescription:
      `The ultimate decentralization: remove the admin key entirely, with cryptographic proof. Contributors add entropy, the ceremony finalizes, and then the private material is provably destroyed via a Wesolowski VDF + keccak-bound destruction proof.\n\nOnce \`destroy\` runs, the state machine can never return to \`idle\`. The language enforces state progression; precompiles at \`0x124..0x127\` enforce the cryptography. This is how a protocol exits its "admin bootstrap" phase into permissionless ossification.`,
    difficulty: 'advanced',
    tags: ['Amnesia', 'security'],
    estimatedReadMinutes: 12,
    prerequisites: ['Understand ceremonies', 'Understand cryptographic commitments'],
    tourLessons: ['M2L5'],
    sourcePath: '15-amnesia-ceremony.cov',
    whatToModify: [
      'Add a minimum contributor count before finalization is allowed',
      'Publish a full contribution transcript with per-round attestations',
      'Build a companion verification contract that other apps can query',
      'Add time bounds (must finalize within N days or ceremony aborts)',
    ],
    relatedExamples: ['D4', 'G5'],
    docsLinks: [
      { title: 'ERC-8228 Amnesia', url: 'https://docs.covenant-lang.org/reference/ercs/erc-8228/' },
    ],
    deployable: true,
    gasEstimate: '~800k gas (ceremony setup)',
    usedInProduction: false,
  },
  {
    id: 'G5',
    category: 'governance',
    order: 5,
    title: 'Guardian Recovery',
    shortDescription: 'Social recovery — N-of-M guardians can rotate ownership if you lose your key.',
    longDescription:
      `The owner designates N trusted guardians. If the owner loses access, a threshold of guardians can collectively rotate ownership to a new address. This is the pattern behind Argent, Safe, and EIP-4337 recovery modules.\n\nThe security tradeoff: you trust the guardians not to collude to steal. Mitigate by choosing uncorrelated parties (family, hardware wallets, a hardware security module, a service provider).`,
    difficulty: 'advanced',
    tags: ['recovery', 'security'],
    estimatedReadMinutes: 8,
    prerequisites: ['Understand maps and structs', 'Understand access control'],
    tourLessons: ['M1L5'],
    sourcePath: '25-guardian-recovery.cov',
    whatToModify: [
      'Add a time delay between initiating recovery and finalizing',
      'Let the owner veto a recovery before it completes',
      'Tier guardians (e.g. 2 family members OR 3 colleagues)',
      'Log an audit trail of every recovery attempt',
    ],
    relatedExamples: ['D4', 'G4'],
    docsLinks: [],
    deployable: true,
    gasEstimate: '~280k gas',
    usedInProduction: true,
  },
];
