import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
// Monaco self-host: MUST run before any <Editor> mounts so the React
// wrapper picks up the bundled instance instead of hitting jsdelivr.
import './lib/monaco-setup';
// Theme bootstrap: applies persisted / system preference to the <html>
// element before React paints so there's no FOUC on dark mode.
import './lib/theme';
// Register the PWA service worker (generated by vite-plugin-pwa at
// build time). Runs in prod only; during `vite dev` this is a no-op
// and the virtual module resolves to an inert shim.
import './lib/register-sw';
import App from './App';
import './styles/globals.css';
import './styles/showcases.css';
import './styles/contract.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
);
